[debug] [2018-11-18T15:47:37.473Z] ----------------------------------------------------------------------
[debug] [2018-11-18T15:47:37.475Z] Command:       /usr/local/bin/node /usr/local/bin/firebase serve
[debug] [2018-11-18T15:47:37.475Z] CLI Version:   6.1.0
[debug] [2018-11-18T15:47:37.475Z] Platform:      darwin
[debug] [2018-11-18T15:47:37.475Z] Node Version:  v8.12.0
[debug] [2018-11-18T15:47:37.476Z] Time:          Sun Nov 18 2018 16:47:37 GMT+0100 (CET)
[debug] [2018-11-18T15:47:37.476Z] ----------------------------------------------------------------------
[debug] 
[debug] [2018-11-18T15:47:37.484Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2018-11-18T15:47:37.484Z] > authorizing via signed-in user
[debug] [2018-11-18T15:47:37.484Z] [iam] checking project baity-test for permissions ["firebase.projects.get"]
[debug] [2018-11-18T15:47:37.486Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/baity-test:testIamPermissions  

[debug] [2018-11-18T15:47:38.488Z] <<< HTTP RESPONSE 200
[debug] [2018-11-18T15:47:38.489Z] >>> HTTP REQUEST GET https://cloudresourcemanager.googleapis.com/v1/projects/baity-test  
 
[debug] [2018-11-18T15:47:39.406Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Volumes/work/Projects/bayty-web-app'...
[info] 
[debug] [2018-11-18T15:47:54.123Z] Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Object.assertLogsPath (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:77:32)
    at FunctionsEmulator.start (/usr/local/lib/node_modules/firebase-tools/lib/functionsEmulator.js:102:23)
    at Object.start (/usr/local/lib/node_modules/firebase-tools/lib/serve/functions.js:7:33)
    at /usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:15:23
    at arrayMap (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9556:14)
    at _serve (/usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:13:26)
    at Command.module.exports.Command.description.option.option.option.option.before.action [as _action] (/usr/local/lib/node_modules/firebase-tools/lib/commands/serve.js:53:12)
[error] 
[error] Error: An unexpected error has occurred.
